from __future__ import annotations

from pathlib import Path

import pandas as pd


BASE = Path(__file__).resolve().parents[1]
JOBS = BASE / "output" / "extraction_jobs"

COLUMNS = [
    "Requirement_ID",
    "Data_Collection_ID",
    "Source_Document_ID",
    "Source_Reference",
    "Original_Text",
    "Atomic_Requirement",
    "Requirement_Type",
    "Actor",
    "Action",
    "Object",
    "Condition",
    "Deadline_or_Frequency",
    "Evidence_Required",
    "BPMN_Element_Type",
    "Extraction_Status",
    "Notes",
]

DC_EAPS = "DC_011_ERSCHWERNISAUSGLEICH_PFLANZENSCHUTZ_EAPS"
SRC_PFLSCHANWV = "SRC_PFLANZENSCHUTZ_ANWENDUNGSVERORDNUNG_PFLSCHANWV"


def write_job(job_name: str, rows: list[dict]) -> None:
    job_dir = JOBS / job_name
    job_dir.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows, columns=COLUMNS).to_csv(
        job_dir / "atomic_requirements_output.csv",
        index=False,
        encoding="utf-8-sig",
    )


def req(
    rid: str,
    ref: str,
    original: str,
    atomic: str,
    rtype: str,
    actor: str,
    action: str,
    obj: str,
    condition: str = "",
    deadline: str = "",
    evidence: str = "",
    bpmn: str = "Task",
    notes: str = "",
) -> dict:
    return {
        "Requirement_ID": rid,
        "Data_Collection_ID": DC_EAPS,
        "Source_Document_ID": SRC_PFLSCHANWV,
        "Source_Reference": ref,
        "Original_Text": original,
        "Atomic_Requirement": atomic,
        "Requirement_Type": rtype,
        "Actor": actor,
        "Action": action,
        "Object": obj,
        "Condition": condition,
        "Deadline_or_Frequency": deadline,
        "Evidence_Required": evidence,
        "BPMN_Element_Type": bpmn,
        "Extraction_Status": "draft_extracted",
        "Notes": notes,
    }


def main() -> None:
    write_job(
        "JOB_LINK_0032_SEC_0001",
        [
            req(
                "PFLSCHANWV-001-001-001",
                "§ 1 PflSchAnwV",
                "dürfen nicht angewandt werden",
                "Pflanzenschutzmittel, die aus einem in Anlage 1 PflSchAnwV aufgeführten Stoff bestehen oder einen solchen Stoff enthalten, dürfen nicht angewandt werden.",
                "Verbot",
                "Anwender",
                "nicht anwenden",
                "Pflanzenschutzmittel mit Stoffen nach Anlage 1 PflSchAnwV",
                "Pflanzenschutzmittel besteht aus einem in Anlage 1 aufgeführten Stoff oder enthält einen solchen Stoff",
                "",
                "Mittelverzeichnis / Wirkstoffprüfung / Gebrauchsanleitung",
                "Business Rule",
            )
        ],
    )

    write_job(
        "JOB_LINK_0032_SEC_0002",
        [
            req(
                "PFLSCHANWV-002-001-001",
                "§ 2 PflSchAnwV",
                "dürfen nur angewandt werden, soweit dies nach Spalte 3 zulässig ist",
                "Pflanzenschutzmittel, die aus einem in Anlage 2 PflSchAnwV aufgeführten Stoff bestehen oder einen solchen Stoff enthalten, dürfen nur angewandt werden, soweit dies nach Anlage 2 Spalte 3 zulässig ist.",
                "Bedingtes Verbot / Anwendungsvorgabe",
                "Anwender",
                "anwenden",
                "Pflanzenschutzmittel mit Stoffen nach Anlage 2 PflSchAnwV",
                "Pflanzenschutzmittel besteht aus einem in Anlage 2 aufgeführten Stoff oder enthält einen solchen Stoff",
                "",
                "Mittelverzeichnis / Wirkstoffprüfung / Gebrauchsanleitung",
                "Gateway; Business Rule",
            )
        ],
    )

    write_job(
        "JOB_LINK_0032_SEC_0003",
        [
            req(
                "PFLSCHANWV-003-001-001",
                "§ 3 Abs. 1 PflSchAnwV",
                "dürfen nicht angewandt werden, soweit dies nach Spalte 3 verboten ist",
                "Pflanzenschutzmittel mit Stoffen aus Anlage 3 Abschnitt A PflSchAnwV dürfen nicht angewandt werden, soweit dies nach Anlage 3 Spalte 3 verboten ist.",
                "Verbot / Anwendungsvorgabe",
                "Anwender",
                "nicht anwenden",
                "Pflanzenschutzmittel mit Stoffen nach Anlage 3 Abschnitt A",
                "Verbot nach Anlage 3 Spalte 3",
                "",
                "Mittelverzeichnis / Wirkstoffprüfung / Gebrauchsanleitung",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-003-002-001",
                "§ 3 Abs. 2 PflSchAnwV",
                "dürfen nicht in Wasserschutzgebieten und Heilquellenschutzgebieten angewandt werden",
                "Pflanzenschutzmittel mit Stoffen aus Anlage 3 Abschnitt B PflSchAnwV dürfen in Wasserschutzgebieten und Heilquellenschutzgebieten nicht angewandt werden, soweit keine Ausnahme nach § 3 Abs. 2 Nr. 1 bis 3 greift.",
                "Verbot / Schutzgebiet",
                "Anwender",
                "nicht anwenden",
                "Pflanzenschutzmittel mit Stoffen nach Anlage 3 Abschnitt B",
                "Wasserschutzgebiet oder Heilquellenschutzgebiet; keine Ausnahme nach § 3 Abs. 2 Nr. 1 bis 3",
                "",
                "Flächenstatus / Schutzgebietskulisse / Mittelverzeichnis",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-003-003-001",
                "§ 3 Abs. 3 PflSchAnwV",
                "auch außerhalb ... nicht angewandt werden dürfen",
                "Wenn die zuständige Behörde ein Anwendungsverbot nach § 3 Abs. 3 PflSchAnwV anordnet, dürfen die betroffenen Pflanzenschutzmittel auch außerhalb von Wasserschutzgebieten und Heilquellenschutzgebieten in den abgegrenzten Gebieten nicht angewandt werden.",
                "Bedingtes Verbot / behördliche Anordnung",
                "Anwender",
                "nicht anwenden",
                "betroffene Pflanzenschutzmittel",
                "behördliche Anordnung für abgegrenzte Einzugsgebiete oder sonstige Gebiete zum Schutz des Grundwassers",
                "",
                "behördliche Anordnung / Flächenkulisse",
                "Gateway; Business Rule",
            ),
        ],
    )

    write_job(
        "JOB_LINK_0032_SEC_0005",
        [
            req(
                "PFLSCHANWV-003B-001-001",
                "§ 3b Abs. 1 PflSchAnwV",
                "sind ... Bedingungen einzuhalten",
                "Bei der Anwendung von Pflanzenschutzmitteln mit Stoffen nach Anlage 3 Abschnitt A Nr. 4 PflSchAnwV müssen neben Zulassungsbestimmungen auch die Bedingungen nach § 3b Abs. 2 bis 5 PflSchAnwV eingehalten werden.",
                "Anwendungsvorgabe",
                "Anwender",
                "einhalten",
                "besondere Anwendungsbedingungen",
                "Pflanzenschutzmittel besteht aus oder enthält Stoff nach Anlage 3 Abschnitt A Nr. 4",
                "",
                "Gebrauchsanleitung / Anwendungsdokumentation",
                "Business Rule",
            ),
            req(
                "PFLSCHANWV-003B-002-001",
                "§ 3b Abs. 2 Satz 1 PflSchAnwV",
                "nur zulässig, wenn ... vorbeugende Maßnahmen ... nicht durchgeführt werden können",
                "Die Anwendung von Pflanzenschutzmitteln nach § 3b Abs. 1 PflSchAnwV ist nur zulässig, wenn vorbeugende Maßnahmen nicht durchgeführt werden können und andere technische Maßnahmen nicht geeignet oder nicht zumutbar sind.",
                "Bedingte Anwendungsvorgabe",
                "Anwender",
                "prüfen",
                "vorbeugende und technische Alternativen",
                "Anwendung von Pflanzenschutzmitteln nach § 3b Abs. 1 PflSchAnwV",
                "",
                "Begründung / Anwendungsdokumentation",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-003B-002-002",
                "§ 3b Abs. 2 Satz 2 PflSchAnwV",
                "auf das notwendige Maß zu beschränken",
                "Aufwandmenge, Anwendungshäufigkeit und behandelte Flächen von Pflanzenschutzmitteln nach § 3b Abs. 1 PflSchAnwV sind auf das notwendige Maß zu beschränken.",
                "Minimierungspflicht",
                "Anwender",
                "beschränken",
                "Aufwandmenge, Anwendungshäufigkeit und behandelte Flächen",
                "Anwendung von Pflanzenschutzmitteln nach § 3b Abs. 1 PflSchAnwV",
                "",
                "Anwendungsdokumentation / Schlagkartei",
                "Business Rule",
            ),
            req(
                "PFLSCHANWV-003B-003-001",
                "§ 3b Abs. 3 PflSchAnwV",
                "Vorsaatbehandlung ... Stoppelbehandlung ist nur zulässig",
                "Eine Anwendung von Pflanzenschutzmitteln nach § 3b Abs. 1 PflSchAnwV zur Vorsaatbehandlung oder nach der Ernte zur Stoppelbehandlung ist nur in den Fällen des § 3b Abs. 3 Nr. 1 oder 2 zulässig.",
                "Bedingte Anwendungsvorgabe",
                "Anwender",
                "anwenden",
                "Pflanzenschutzmittel zur Vorsaat- oder Stoppelbehandlung",
                "nur Bekämpfung perennierender Unkrautarten auf Teilflächen oder Unkrautbekämpfung auf erosionsgefährdeten Ackerflächen; Direktsaat-/Mulchsaat-Ausnahme beachten",
                "",
                "Anwendungsdokumentation / Flächenstatus",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-003B-004-001",
                "§ 3b Abs. 4 PflSchAnwV",
                "flächige Anwendung ... auf Grünland ist nur zulässig",
                "Eine flächige Anwendung von Pflanzenschutzmitteln nach § 3b Abs. 1 PflSchAnwV auf Grünland ist nur in den Fällen des § 3b Abs. 4 Nr. 1 bis 3 zulässig.",
                "Bedingte Anwendungsvorgabe",
                "Anwender",
                "anwenden",
                "flächige Anwendung auf Grünland",
                "nur bei Grünlanderneuerung wegen erheblicher Verunkrautung, Vorbereitung einer Neueinsaat auf bestimmten Flächen oder Bekämpfung invasiver Arten bzw. Quarantäneschädlinge",
                "",
                "Anwendungsdokumentation / Begründung / Flächenstatus",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-003B-004-002",
                "§ 3b Abs. 4 Satz 2 PflSchAnwV",
                "auf die betroffenen Teilflächen ... zu beschränken",
                "Bei Anwendung nach § 3b Abs. 4 Satz 1 Nr. 1 PflSchAnwV ist die Anwendung auf die betroffenen Teilflächen des Grünlands zu beschränken.",
                "Minimierungspflicht",
                "Anwender",
                "beschränken",
                "Anwendung auf Grünland",
                "Grünlanderneuerung wegen Verunkrautung nach § 3b Abs. 4 Satz 1 Nr. 1",
                "",
                "Flächendokumentation / Anwendungsdokumentation",
                "Business Rule",
            ),
            req(
                "PFLSCHANWV-003B-005-001",
                "§ 3b Abs. 5 PflSchAnwV",
                "Spätanwendung ... nicht zulässig",
                "Eine Spätanwendung von Pflanzenschutzmitteln nach § 3b Abs. 1 PflSchAnwV vor der Ernte ist nicht zulässig.",
                "Verbot",
                "Anwender",
                "nicht anwenden",
                "Spätanwendung vor der Ernte",
                "Pflanzenschutzmittel nach § 3b Abs. 1 PflSchAnwV",
                "",
                "Anwendungsdokumentation",
                "Business Rule",
            ),
            req(
                "PFLSCHANWV-003B-005-002",
                "§ 3b Abs. 5 PflSchAnwV",
                "Anwendung in Wasserschutzgebieten ... nicht zulässig",
                "Die Anwendung von Pflanzenschutzmitteln nach § 3b Abs. 1 PflSchAnwV in Wasserschutzgebieten, Heilquellenschutzgebieten sowie Kern- und Pflegezonen von Biosphärenreservaten ist nicht zulässig.",
                "Verbot / Schutzgebiet",
                "Anwender",
                "nicht anwenden",
                "Pflanzenschutzmittel nach § 3b Abs. 1 PflSchAnwV",
                "Wasserschutzgebiet, Heilquellenschutzgebiet oder Kern-/Pflegezone eines Biosphärenreservats",
                "",
                "Flächenstatus / Schutzgebietskulisse / Anwendungsdokumentation",
                "Business Rule",
            ),
        ],
    )

    write_job(
        "JOB_LINK_0032_SEC_0006",
        [
            req(
                "PFLSCHANWV-004-001-001",
                "§ 4 Abs. 1 Satz 1 PflSchAnwV",
                "dürfen ... nicht angewendet werden",
                "In Naturschutzgebieten, Nationalparken, Nationalen Naturmonumenten, Naturdenkmälern und gesetzlich geschützten Biotopen dürfen die in § 4 Abs. 1 Satz 1 Nr. 1 bis 3 PflSchAnwV genannten Pflanzenschutzmittel nicht angewendet werden.",
                "Verbot / Schutzgebiet",
                "Anwender",
                "nicht anwenden",
                "bestimmte Pflanzenschutzmittel",
                "Naturschutzgebiet, Nationalpark, Nationales Naturmonument, Naturdenkmal oder gesetzlich geschütztes Biotop; Ausnahme Trockenmauern im Weinbau",
                "",
                "Flächenstatus / Schutzgebietskulisse / Mittelverzeichnis",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-004-001-002",
                "§ 4 Abs. 1 Satz 2 PflSchAnwV",
                "gelten auch in Gebieten von gemeinschaftlicher Bedeutung",
                "Die Verbote nach § 4 Abs. 1 Satz 1 PflSchAnwV gelten auch in Gebieten von gemeinschaftlicher Bedeutung, soweit keine genannte Ausnahme greift.",
                "Verbot / Schutzgebiet",
                "Anwender",
                "nicht anwenden",
                "bestimmte Pflanzenschutzmittel",
                "Gebiet von gemeinschaftlicher Bedeutung; Ausnahmen für bestimmte Nutzungen und Ackerflächen beachten",
                "",
                "Flächenstatus / Schutzgebietskulisse",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-004-002-001",
                "§ 4 Abs. 2 PflSchAnwV",
                "kann Ausnahmen ... zulassen",
                "Eine Anwendung entgegen den Verboten nach § 4 Abs. 1 PflSchAnwV darf nur erfolgen, wenn eine zulässige Ausnahme der zuständigen Behörde vorliegt; dies gilt nicht für Mittel mit Stoffen nach Anlage 3 Abschnitt A Nr. 4.",
                "Bedingte Erlaubnis / Genehmigung",
                "Anwender",
                "Genehmigung einholen",
                "Ausnahme von Anwendungsverboten in Schutzgebieten",
                "Verbot nach § 4 Abs. 1 PflSchAnwV; Ausnahmegründe nach § 4 Abs. 2 Nr. 1 bis 3",
                "",
                "Ausnahmegenehmigung",
                "Gateway; Task",
            ),
        ],
    )

    write_job(
        "JOB_LINK_0032_SEC_0007",
        [
            req(
                "PFLSCHANWV-004A-001-001",
                "§ 4a Abs. 1 Satz 1 PflSchAnwV",
                "innerhalb eines Abstandes von zehn Metern ... nicht angewendet",
                "Pflanzenschutzmittel dürfen an Gewässern innerhalb eines Abstandes von zehn Metern zum Gewässer nicht angewendet werden.",
                "Verbot / Gewässerabstand",
                "Anwender",
                "nicht anwenden",
                "Pflanzenschutzmittel",
                "Gewässer, ausgenommen kleine Gewässer von wasserwirtschaftlich untergeordneter Bedeutung; Abstand gemessen ab Böschungsoberkante oder Linie des Mittelwasserstandes",
                "10 Meter Abstand",
                "Flächen-/Gewässerabstandsdokumentation",
                "Business Rule",
            ),
            req(
                "PFLSCHANWV-004A-001-002",
                "§ 4a Abs. 1 Satz 2 PflSchAnwV",
                "Mindestabstand fünf Meter",
                "Der Mindestabstand bei der Anwendung von Pflanzenschutzmitteln an Gewässern beträgt fünf Meter, wenn eine geschlossene, ganzjährig begrünte Pflanzendecke vorhanden ist.",
                "Bedingte Gewässerabstandsregel",
                "Anwender",
                "einhalten",
                "Mindestabstand",
                "geschlossene, ganzjährig begrünte Pflanzendecke vorhanden",
                "5 Meter Abstand",
                "Flächen-/Gewässerabstandsdokumentation / Begrünungsnachweis",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-004A-001-003",
                "§ 4a Abs. 1 Satz 3 PflSchAnwV",
                "Bodenbearbeitung ... einmal innerhalb von Fünfjahreszeiträumen",
                "Eine Bodenbearbeitung zur Erneuerung des Pflanzenbewuchses im Gewässerabstandsbereich darf nur einmal innerhalb eines Fünfjahreszeitraums durchgeführt werden.",
                "Beschränkung / Frequenz",
                "Bewirtschafter / Anwender",
                "beschränken",
                "Bodenbearbeitung zur Erneuerung des Pflanzenbewuchses",
                "Gewässerabstandsbereich nach § 4a PflSchAnwV",
                "einmal je Fünfjahreszeitraum",
                "Flächen-/Arbeitsdokumentation",
                "Business Rule; Timer Event",
            ),
            req(
                "PFLSCHANWV-004A-001-004",
                "§ 4a Abs. 1 Satz 5 PflSchAnwV",
                "bleibt die Pflicht zur Einhaltung ... unberührt",
                "Sind für ein Pflanzenschutzmittel größere Abstände oder bestimmte Pflanzenschutzgeräte als Anwendungsbestimmungen festgelegt, müssen diese Anwendungsbestimmungen zusätzlich eingehalten werden.",
                "Anwendungsvorgabe",
                "Anwender",
                "einhalten",
                "Anwendungsbestimmungen zu Abstand oder Gerät",
                "Zulassung des jeweiligen Pflanzenschutzmittels enthält strengere Abstandsvorgaben oder Gerätevorgaben",
                "",
                "Gebrauchsanleitung / Zulassung / Anwendungsdokumentation",
                "Gateway; Business Rule",
            ),
            req(
                "PFLSCHANWV-004A-002-001",
                "§ 4a Abs. 2 PflSchAnwV",
                "kann Ausnahmen ... genehmigen",
                "Eine Anwendung entgegen § 4a Abs. 1 Satz 1 oder 2 PflSchAnwV darf nur erfolgen, wenn die zuständige Behörde eine Ausnahme genehmigt.",
                "Bedingte Erlaubnis / Genehmigung",
                "Anwender",
                "Genehmigung einholen",
                "Ausnahme vom Gewässerabstandsverbot",
                "Abwendung erheblicher landwirtschaftlicher, forstwirtschaftlicher oder sonstiger wirtschaftlicher Schäden oder Schutz der heimischen Tier- und Pflanzenwelt",
                "",
                "Ausnahmegenehmigung",
                "Gateway; Task",
            ),
        ],
    )

    write_job(
        "JOB_LINK_0032_SEC_0010",
        [
            req(
                "PFLSCHANWV-007-001-001",
                "§ 7 Abs. 1 PflSchAnwV",
                "kann ... genehmigen",
                "Eine Anwendung von Pflanzenschutzmitteln abweichend von §§ 1 bis 3 PflSchAnwV für Forschungs-, Untersuchungs- oder Versuchszwecke darf nur erfolgen, wenn das Bundesamt für Verbraucherschutz und Lebensmittelsicherheit sie genehmigt.",
                "Bedingte Erlaubnis / Genehmigung",
                "Anwender / Antragsteller",
                "Genehmigung einholen",
                "Ausnahme für Forschungs-, Untersuchungs- oder Versuchszwecke",
                "Anwendung außerhalb von Wasserschutzgebieten und Heilquellenschutzgebieten; Abweichung von §§ 1 bis 3 PflSchAnwV",
                "",
                "BVL-Genehmigung",
                "Gateway; Task",
            ),
            req(
                "PFLSCHANWV-007-002-001",
                "§ 7 Abs. 2 Nr. 1 PflSchAnwV",
                "soweit durch Schutzvorkehrungen sichergestellt ist",
                "Eine Anwendung bestimmter Pflanzenschutzmittel in Gewächshäusern oder ähnlich geschlossenen Systemen in Wasserschutzgebieten oder Heilquellenschutzgebieten darf nur mit Einzelfallgenehmigung der zuständigen Behörde erfolgen und nur, wenn Schutzvorkehrungen Abschwemmung oder Versickerung verhindern.",
                "Bedingte Erlaubnis / Genehmigung",
                "Anwender / Antragsteller",
                "Genehmigung einholen und Schutzvorkehrungen sicherstellen",
                "Pflanzenschutzmittel in Gewächshäusern oder geschlossenen Systemen",
                "Abweichung von § 2 oder § 3 Abs. 2 PflSchAnwV in Wasserschutzgebiet oder Heilquellenschutzgebiet",
                "",
                "Genehmigung / Schutzvorkehrungsnachweis",
                "Gateway; Task",
            ),
            req(
                "PFLSCHANWV-007-002-002",
                "§ 7 Abs. 2 Nr. 2 PflSchAnwV",
                "wenn sichergestellt ist ... nicht beeinträchtigt wird",
                "Eine Anwendung bestimmter Pflanzenschutzmittel in Wasserschutzgebieten oder Heilquellenschutzgebieten darf im Einzelfall nur mit Genehmigung der zuständigen Behörde im Einvernehmen mit der Wasserbehörde erfolgen, wenn der Schutz von Mensch, Tier, Grundwasser und Naturhaushalt nicht beeinträchtigt wird.",
                "Bedingte Erlaubnis / Genehmigung",
                "Anwender / Antragsteller",
                "Genehmigung einholen",
                "Pflanzenschutzmittel in Wasserschutzgebieten oder Heilquellenschutzgebieten",
                "Abweichung von § 2 oder § 3 Abs. 2 PflSchAnwV",
                "",
                "Genehmigung / wasserrechtliche Abstimmung",
                "Gateway; Task",
            ),
        ],
    )

    print("Fourth batch extraction drafts written.")


if __name__ == "__main__":
    main()
